const án = "judgement, sentence, verdict, to examine";
const công = "to be public, common";

const vocab_1 = {
  và: "and",
  tái: "again, re",
  tạo: "to create, to make",
  của: "of",
  trái: "fruit cake",
  đất: "land",
  trái_đất: "earth",
  một: "one",
  án,
  công,
  công_án: án + " " + công,
  về: "about, of",
  thiên_mệnh: "mandate of heaven",
  thiên: "heaven",
  mệnh: "life, Gods's will, destiny, fate",
  công_án_thiền: "meditation",
  thiền: "meditate",
  Phật: "Buddha",
  là: "is, to be",
  gì: "what",
  bí: "secret",
  quyết: "secret",
  bí_quyết: "secret",
  sửa: "to repair, fix, mend, correct, amend",
  đổi: "change",
  vận: "luck; destiny, fate",
  mệnh: "life",
  vận_mệnh: "life's luck",
  nguyên_lý: "principle",
  nguồn: "source",
  lý: "reason, ground, common sense, argument",
  tôn: "a religious group that exists inside of a larger religion. Think of it as a section of a particular religion. or ancestor",
  tôn_chỉ: "aim, purpose",
  diễn_đàn: "forum",
  diễn: "to perform, to relate, explicate",
  đàn: "to press, flock, herd, school, band, group",
  bài: "post",
  cần: "need",
  xem: "to see",
  bài_cần_xem: "posted to see",
  gặp: "meet",
  tại: "at",
  thế: "the world",
  đời: "the world; life; age, generation, posterity",
  thế_gian: "dishonest, cheating, tricky, crooked",
  thế_giới: "limit, border, world realm",
  trần: "world, life",
  bụi: "dust",
  đại: "big, great",
  nguyên_tắc: "rule, principle",
  tế: "to offer heart sacrifices to",
  trời: "god",
  thien_cỏ: "god's plan",
  cho: "for",
  giới_thiệu: "to introduce",
  thiệu: "introduction",
  giới: "limit, border, world, circles; realm",
  tông: "sect, school",
  Mật_tông:
    "dharma derived into two factions:The True Language (Mantrayàna) and the Excess Diamond (Vajrayàna).",
  người: "man, person, individual",
  người_ta: "people",
  ta: "me",
  khu_vực: "area",
  khu: "area, district, zone, section, sector",
  vực: "area, field",
  tiếng: "language",
  việt: "Vietnam",
  thông_báo: "notification, to announce",
  thông: "to communicate, to go through, to penetrate",
  báo: "announce, to inform",
  nội: "inside, internal",
  quy: "regulations",
  nội_quy: "rules and regulations",
  hướng: "direction",
  dẫn: "guide",
  hướng_dẫn: "tutorial",
  diều_kiện: "conditions, requirements",
  diều: "thing, matter, detail, action, circumstance, affair article", // article
  kiện: "package, parcel, bale", // package
  điểm_đạo: "initiation",
  điểm: "point",
  đạo: "religion way, spirituality",
  tài_khoản: "account",
  tài: "money",
  thắc_mắc: "question",
  thắc: "tie",
  mắc: "to be caught, entangled in",
  mật: "secret",
  pháp: "dharma",
  đình: "court",
  thiên_đình: "heaven court",
  hộp: "box",
  thư: "letters",
  thơ: "poem",
  hộp_thư: "mailbox",
  giáo: "teaching, tantra",
  thần: "angel, deity (mystery)",
  thần_bí: "mystery",
  thầy: "teacher",
  già: "old",
  cư_sĩ: "buddhist term.",
  cư: "at home, reside",
  sĩ: "practitioner",
  nhiệm_mầu: "Miraculous",
  những: "(classifier) for more than one. plural, many",
  lọc: "filter",
  chọn: "choose",
  chọn_lọc: "selective, select",
  thảo: "tham khảo -> to do research, to reference",
  khảo_cứu: "research",
  ly_luận: "reasoning",
  luận: "reasoning",
  tổng: "total",
  hợp: "together",
  tổng_hợp: "synthesis, synthetic",
  theo: "according to",
  chư: "subject",
  đề: "topic",
  giảng: "lecture",
  ấn: "seal",
  chứng: "chứng cỏ = evidence, proof",
  tối: "dark, night",
  khải: "revelation",
  lễ: "ceremony",
  nhận: "receive",
  lá: "leaf",
  thiên_thơ: "heaven scroll",
  lá_thiên_thơ: "heaven scroll",
  thơ: "mail",
  phép_mầu: "mircale",
  phép_lạ: "magic",
  cầu: "beg",
  tức: "to mean",
  hìện: "show",
  thị: "seeing",
  thị_hìện: "make appearance",
  thánh_thần: "holy spirit",
  học: "study",
  nhật_ký: "diary",
  nhật: "daily",
  ký: "writing",
  tu: "cultivate the ways",
  nay: "today",
  tối_nay: "tonight",
  giấc_mơ: "dream",
  giấc: "sleeping",
  mơ: "dream",
  linh: "sacred",
  ảnh: "image",
  đặc_biệt: "special, typical",
  đặc: "special",
  biệt: "separated, isolated, special",
  bài_học: "lessons",
  từ: "from",
  vô: "zero",
  hình: "image",
  vô_hình: "invisible",
  ân: "kind act, good deed, favor",
  ân_phước: "blessing",
  phước: "blessing",
  hành: "practice",
  hành_đạo: "practice religion",
  thực_hành: "practice",
  báo_cáo: "report",
  cáo: "announce, report",
  thị: "seeing",
  chấm_điểm: "give grade",
  cúng: "to make ceremony",
  cúng_dường: "to make ceremonial offerings",
  thành_tích: "achievements",
  thành: "to become, as a result, to complete",
  tích: "to accumulate, to merit",
  chuyện: "story",
  tâm: "heart",
  linh_hồn: "soul",
  linh_ứng: "to have supernatural power",
  tâm_linh: "spirituality",
  có: "have",
  thật: "true, real",
  huyền: "miraculous",
  ma: "ghost",
  khoa_học: "science",
  không: "cannot, zero",
  lý_giải: "explain",
  giải: "decode",
  giải_thich: "explain",
  khoa: "subject of study, specialty, branch of college faculty",
  mới: "new",
  tài_liệu: "material, document or data",
  tài: "riches, wealth, money",
  cập_nhật: "update",
  cập: "updated",
  nhật: "daily",
  tin_tức: "news",
  quốc_tế: "international",
  dời_sống: "life, living",
  dời: "life",
  sống: "to live, to be living, alive",
  sức: "strength",
  sức_khỏe: "strong, healthy",
  khỏe: "strong",
  sức_lực: "strength",
  phim: "movie",
  nhạc: "music",
  nghệ_thuật: "art",
  nghệ: "profession, occupation",
  thuật: "to relate, narrate, recount, tell, repeat",
  cuộc_đời: "life",
  cuộc: "situation",
  sự: "affair, event, thing, matter, denoting actions, events, states",
  khỏe_dẹp: "healthy and beauty",
  võ_thuật: "martial art, art of fighting, to be military",
  sưu: "collection",
  tầm: "look for",
  tìm: "find, look for",
  trích: "to pick, to pick out",
  dịch: "translate",
  kinh_sách: "scriptures, sutra, bible",
  sách: "book",
  tinh: "to be fine, pure",
  hoa: "flower, blossom, bloom",
  tinh_hoa: "essence, quintessence",
  phong: "to name",
  tư_tưởng: "thought",
  tư: "to think",
  phật_tử: "buddhist",
  tử: "son",
  dương_tú_hạc: "is a name",
  nữ: "female",
  toa: "sit, seat",
  thượng: "high",
  trăc_nghiệm: "to test, to measure",
  nghiệm: "to experiment, examine, inspect, experience",
  náy: "this",
  kinh: "sutra, bible",
  nhiều: "many, alot of, much",
  trở_về: "return",
  liên_kết: "to unite associate with",
  liên: "to joiin, associate, unite, ally",
  kết: "to fasten together",
  tìm_kiếm: "to seek, look for, search for",
  tìm: "to seek, look for, search for",
  kiếm: "to seek, look for, search for",
  vũ: "space  (related to)",
  trụ: "time (related to)",
  tất_cả: "all",
  bài_viết: "writings, posts",
  bài: "lesson",
  trên: "on",
  đăng: "to post",
  được: "acceptable, fine, O.K",
  vũ_trụ: "the universe",
  đều: "equal, even, regular, same",
  thuộc: "to belong to",
  quyền: "power, authority",
  sở_hữu: "to own, ownership",
  sở: "place of work, office, bueau, service, department",
  hữu: "to have, own",
  trang: "page",
  nhà: "home",
  ban_điều_hành: "executive board",
  ban: "department, section, division, unit, board, committee, commission",
  điều: "to arrange, order, direct",
  hành: "act, execute",
  toàn: "to be entire, whole, total, complete.",
  xóa: "to erase, crossout, annul",
  kiểm: "to verify, check, control, examine, inspect",
  duyệt: "to examine, inspect, review, censor",
  hay: "or",
  khóa: "lock",
  tài: "referred to material",
  khoản: "article, item, clause, condition, term",
  mà: "but, yet and, so that, so as to, that, which",
  má: "mother",
  nếu: "if",
  nội_dung: "containment",
  nội: "inside",
  dung: "to contain",
  gởi: "to send, forward, remit, dispatch",
  phù_hợp: "suitable",
  với: "with",
  vui: "joyful, merry",
  lòng: "heart; feelings",
};

console.log(vocab_1);
