const án = "judgement, sentence, verdict, to examine";
const công = "to be public, common";

const vocab_1 = {
  và: "and",
  tái: "again, re",
  tạo: "to create, to make",
  của: "of",
  trái: "fruit cake",
  đất: "land",
  trái_đất: "earth",
  một: "one",
  án,
  công,
  công_án: án + " " + công,
  về: "about",
  thiên_mệnh: "mandate of heaven",
  thiên: "heaven",
  mệnh: "life, Gods's will, destiny, fate",
  công_án_thiền: "meditation",
  thiền: "meditate",
  Phật: "Buddha",
  là: "is, to be",
  gì: "what",
  bí: "secret",
  quyết: "secret",
  bí_quyết: "secret",
  sửa: "to repair, fix, mend, correct, amend",
  đổi: "change",
  vận: "luck; destiny, fate",
  mệnh: "life",
  vận_mệnh: "life's luck",
  nguyên_lý: "principle",
  nguồn: "source",
  lý: "reason, ground, common sense, argument",
  tôn: "a religious group that exists inside of a larger religion. Think of it as a section of a particular religion. or ancestor",
  tôn_chỉ: "aim, purpose",
  diễn_đàn: "forum",
  diễn: "to perform, to relate, explicate",
  đàn: "to press, flock, herd, school, band, group",
  bài: "lesson",
  cần: "need",
  xem: "to see",
  bài_cần_xem: "posted to see",
  gặp: "meet",
  tại: "at",
  thế: "the world",
  đời: "the world; life; age, generation, posterity",
  thế_gian: "dishonest, cheating, tricky, crooked",
  thế_giới: "limit, border, world realm",
  trần: "world, life",
  bụi: "dust",
  đại: "big, great",
  nguyên_tắc: "rule, principle",
  tế: "to offer heart sacrifices to",
  trời: "god",
  thien_cỏ: "god's plan",
  cho: "for",
  giới_thiệu: "to introduce",
  thiệu: "introduction",
  giới: "limit, border, world, circles; realm",
  tông: "sect, school",
  Mật_tông:
    "dharma derived into two factions:The True Language (Mantrayàna) and the Excess Diamond (Vajrayàna).",
};

console.log(vocab_1);
