const án = "judgement, sentence, verdict, to examine";
const công = "to be public, common";

const vocab_1 = {
  và: "and",
  tái: "again, re",
  tạo: "to create, to make",
  của: "of",
  trái: "fruit cake",
  đất: "land",
  trái_đất: "earth",
  một: "one",
  án,
  công,
  công_án: án + " " + công,
  về: "about, of, to",
  thiên_mệnh: "mandate of heaven",
  thiên: "heaven",
  mệnh: "life, Gods's will, destiny, fate",
  công_án_thiền: "meditation",
  thiền: "meditate",
  Phật: "Buddha",
  là: "is, to be",
  gì: "what",
  bí: "secret",
  quyết: "secret",
  bí_quyết: "secret",
  sửa: "to repair, fix, mend, correct, amend",
  đổi: "change",
  vận: "luck; destiny, fate",
  mệnh: "life",
  vận_mệnh: "life's luck",
  nguyên_lý: "principle",
  nguồn: "source",
  lý: "reason, ground, common sense, argument",
  tôn: "a religious group that exists inside of a larger religion. Think of it as a section of a particular religion. or ancestor",
  tôn_chỉ: "aim, purpose",
  diễn_đàn: "forum",
  diễn: "to perform, to relate, explicate",
  đàn: "to press, flock, herd, school, band, group",
  bài: "post",
  cần: "need",
  xem: "to see",
  bài_cần_xem: "posted to see",
  gặp: "meet",
  tại: "at",
  thế: "the world",
  đời: "the world; life; age, generation, posterity",
  thế_gian: "dishonest, cheating, tricky, crooked",
  thế_giới: "limit, border, world realm",
  trần: "world, life",
  bụi: "dust",
  đại: "big, great",
  nguyên_tắc: "rule, principle",
  tế: "to offer heart sacrifices to",
  trời: "god",
  thien_cỏ: "god's plan",
  cho: "for; to give, to add, to, as a favor, for you",
  giới_thiệu: "to introduce",
  thiệu: "introduction",
  giới: "limit, border, world, circles; realm",
  tông: "sect, school",
  Mật_tông:
    "dharma derived into two factions:The True Language (Mantrayàna) and the Excess Diamond (Vajrayàna).",
  người: "man, person, individual",
  người_ta: "people",
  ta: "me",
  khu_vực: "area",
  khu: "area, district, zone, section, sector",
  vực: "area, field",
  tiếng: "language, noise; sound, voice, repuation, fame; houl",
  việt: "Vietnam",
  thông_báo: "notification, to announce",
  thông: "to communicate, to go through, to penetrate",
  báo: "announce, to inform",
  nội: "inside, internal",
  quy: "regulations",
  nội_quy: "rules and regulations",
  hướng: "direction",
  dẫn: "guide",
  hướng_dẫn: "tutorial",
  diều_kiện: "conditions, requirements",
  diều: "thing, matter, detail, action, circumstance, affair article", // article
  kiện: "package, parcel, bale", // package
  điểm_đạo: "initiation",
  điểm: "point",
  đạo: "religion way, spirituality",
  tài_khoản: "account",
  tài: "money",
  thắc_mắc: "question",
  thắc: "tie",
  mắc: "to be caught, entangled in",
  mật: "secret",
  pháp: "dharma",
  đình: "court",
  thiên_đình: "heaven court",
  hộp: "box",
  thư: "letters",
  thơ: "poem",
  hộp_thư: "mailbox",
  giáo: "teaching, tantra",
  thần: "angel, deity (mystery)",
  thần_bí: "mystery",
  thầy: "teacher",
  già: "old",
  cư_sĩ: "buddhist term.",
  cư: "at home, reside",
  sĩ: "practitioner",
  nhiệm_mầu: "Miraculous",
  những: "(classifier) for more than one. plural, many",
  lọc: "filter",
  chọn: "choose",
  chọn_lọc: "selective, select",
  thảo: "tham khảo -> to do research, to reference",
  khảo_cứu: "research",
  ly_luận: "reasoning",
  luận: "reasoning",
  tổng: "total, as a noun-> canton, district; general",
  hợp: "together",
  tổng_hợp: "synthesis, synthetic",
  theo: "according to",
  chư: "subject",
  đề: "topic",
  giảng: "lecture",
  ấn: "seal",
  chứng: "chứng cỏ = evidence, proof",
  tối: "dark, night",
  khải: "revelation",
  lễ: "ceremony",
  nhận: "receive",
  lá: "leaf",
  thiên_thơ: "heaven scroll",
  lá_thiên_thơ: "heaven scroll",
  thơ: "mail",
  phép_mầu: "mircale",
  phép_lạ: "magic",
  cầu: "beg",
  tức: "to mean",
  hìện: "show",
  thị: "seeing",
  thị_hìện: "make appearance",
  thánh_thần: "holy spirit",
  học: "study",
  nhật_ký: "diary",
  nhật: "daily",
  ký: "writing",
  tu: "cultivate the ways",
  nay: "today",
  tối_nay: "tonight",
  ngày_mai: "tomorrow",
  ngày: "day",
  mỗi_ngày: "everyday",
  giấc_mơ: "dream",
  giấc: "sleeping, pass out, nap, dream",
  ngủ: "sleep",
  mơ: "dream",
  linh: "sacred",
  ảnh: "image",
  đặc_biệt: "special, typical",
  đặc: "special",
  biệt: "separated, isolated, special",
  bài_học: "lessons",
  từ: "from",
  vô: "zero, none",
  hình: "image",
  vô_hình: "invisible",
  ân: "kind act, good deed, favor",
  ân_phước: "blessing",
  phước: "blessing",
  hành: "practice, act, execute, carryout",
  hành_đạo: "practice religion",
  thực_hành: "practice",
  báo_cáo: "report",
  cáo: "announce, report; to indict",
  chấm_điểm: "give grade",
  cúng: "to make ceremony",
  cúng_dường: "to make ceremonial offerings",
  thành_tích: "achievements",
  thành: "to become, as a result, to complete",
  tích: "to accumulate, to merit",
  chuyện: "story",
  tâm: "heart",
  linh_hồn: "soul",
  linh_ứng: "to have supernatural power",
  tâm_linh: "spirituality",
  có: "have; to exist; possess; own",
  thật: "true, real",
  huyền: "miraculous",
  ma: "ghost",
  khoa_học: "science",
  không: "cannot, zero",
  lý_giải: "explain",
  giải: "decode",
  giải_thich: "explain",
  khoa: "subject of study, specialty, branch of college faculty",
  mới: "new",
  tài_liệu: "material, document or data",
  tài: "riches, wealth, money",
  cập_nhật: "update",
  cập: "updated",
  tin_tức: "news",
  quốc_tế: "international",
  dời_sống: "life, living",
  dời: "life",
  sống: "to live, to be living, alive",
  sức: "strength",
  sức_khỏe: "strong, healthy",
  khỏe: "strong",
  sức_lực: "strength",
  phim: "movie",
  nhạc: "music",
  nghệ_thuật: "art",
  nghệ: "profession, occupation",
  thuật: "to relate, narrate, recount, tell, repeat",
  cuộc_đời: "life",
  cuộc: "situation",
  sự: "affair, event, thing, matter, denoting actions, events, states",
  khỏe_dẹp: "healthy and beauty",
  võ_thuật: "martial art, art of fighting, to be military",
  sưu: "collection",
  tầm: "look for",
  tìm: "find, look for",
  trích: "to pick, to pick out",
  dịch: "translate",
  kinh_sách: "scriptures, sutra, bible",
  sách: "book",
  tinh: "to be fine, pure",
  hoa: "flower, blossom, bloom",
  tinh_hoa: "essence, quintessence",
  phong: "to name",
  tư_tưởng: "thought",
  tư: "to think",
  phật_tử: "buddhist",
  dương_tú_hạc: "is a name",
  nữ: "female",
  toa: "sit, seat",
  thượng: "high",
  trăc_nghiệm: "to test, to measure",
  nghiệm: "to experiment, examine, inspect, experience",
  náy: "this",
  kinh: "sutra, bible",
  nhiều: "many, alot of, much",
  trở_về: "return",
  liên_kết: "to unite associate with",
  liên: "to joiin, associate, unite, ally",
  kết: "to fasten together",
  tìm_kiếm: "to seek, look for, search for",
  tìm: "to seek, look for, search for",
  kiếm: "to seek, look for, search for",
  vũ: "space  (related to)",
  trụ: "time (related to)",
  tất_cả: "all",
  bài_viết: "writings, posts",
  bài: "lesson",
  trên: "on",
  đăng: "to post",
  được: "acceptable, fine, O.K",
  vũ_trụ: "the universe",
  đều: "equal, even, regular, same",
  thuộc: "to belong to",
  quyền: "power, authority",
  sở_hữu: "to own, ownership",
  sở: "place of work, office, bueau, service, department",
  hữu: "to have, own",
  trang: "page",
  nhà: "home",
  ban_điều_hành: "executive board",
  ban: "department, section, division, unit, board, committee, commission",
  điều: "to arrange, order, direct",
  hành: "act, execute",
  toàn: "to be entire, whole, total, complete.",
  xóa: "to erase, crossout, annul",
  kiểm: "to verify, check, control, examine, inspect",
  duyệt: "to examine, inspect, review, censor",
  hay: "or",
  khóa: "lock",
  tài: "referred to material",
  khoản: "article, item, clause, condition, term",
  mà: "but, yet and, so that, so as to, that, which",
  má: "mother",
  nếu: "if",
  nội_dung: "containment",
  nội: "inside",
  dung: "to contain",
  gởi: "to send, forward, remit, dispatch",
  phù_hợp: "suitable",
  với: "with",
  vui: "joyful, merry",
  lòng: "heart; feelings",
  ghi_lại: "to record, note",
  lại: "again",
  xuất_xứ: "origin",
  xuất: "to advance, to exit, go out, come out",
  xứ: "region, area, locality, district, country, nation",
  khi: "when",
  qúy: "noble, valuable, precious",
  vị: "seat, condition, rank, position",
  nhằm: "to aim at, hit, occur on",
  phổ_biến: "common to all, to be universal (popular)",
  vô_vụ_lợi: "non-profit",
  vụ: "business, duty, affairs",
  lợi: "profit",
  xin: "ask, beg",
  các: "all, the various",
  hỏi: "question",
  khác: "other",
  chủ: "owner, master, boss, lord",
  thượng_dế: "god",
  chấp: "to hold",
  ngã: "ego",
  hòa_thượng: "monk",
  thượng: "upper, on, above",
  hòa: "to mix, blend with",
  thiên_cơ: "divine plan",
  cơ: "machine",
  bộ_máy: "machine",
  diệt: "destory, exterminate",
  hủy_diệt: "destroy",
  hủy: "to destory, ruin, cancel, annul",
  yếu_lược: "summary",
  yếu: "essential, important",
  lược: "summary",
  quyển: "volumne, book",
  trung: "middle, center, interior",
  sư: "teacher",
  tổ: "founder",
  di_sản: "inherited property; haritage",
  di: "to sustain, nourish",
  sản: "to produce, to reproduce, property",
  tài_sản: "assets",
  nền: "base, foundation, basis; background",
  dạo: "religion, the way",
  độ: "to save, help, aid",
  quốc: "country",
  nước: "country",
  địa: "geography, earth",
  dất: "earth",
  địa_mâữ: "mother earth",
  thần_khãi: "revelations  (magic)",
  nam: "south",
  sơn: "mountain",
  hà: "river",
  chân: "real",
  thân: "body, life, existence",
  mình: "body, life existence",
  đức: "his majesty, his holiness",
  đức_sư: "the grand master",
  tòa: "palace",
  tháp: "tower",
  thảo_luận: "to discuss",
  thảo: "to examine",
  luận: "to duscuss, consider, comment",
  chọn_lọc: "to select, selective",
  chọn: "to choose, to select",
  lọc: "to filter",
  sổ: "notebook, register; account book",
  giũ: "to shake the dust or water off",
  gửi_bởi: "send by",
  gửi: "to send",
  bởi: "by",
  xủ: "to be hanging, to be flowing",
  mu: "shell of a turtle",
  rùa: "turtle",
  tháng: "month",
  chủ_nhật: "sunday",
  nhật: "day",
  thời_gian: "time",
  thời: "time",
  gian: "space",
  thì: "time",
  thì_giờ: "time",
  qua: "past",
  qua_thấy: "over see",
  nhân_vật: "figure, personage",
  chính_trị: "politics",
  chính: "to administer, govern",
  trị: "to administer, govern, rule",
  quân_sự: "military, army",
  tướng: "general",
  tướng_lảnh: "general",
  lảnh: "to lead, command",
  nổi_tiếng: "popular",
  nổi: "to rise, to surface, emerge, float",
  tiếng_tăm: "reputation",
  tăm: "trace",
  bị: "to be",
  đột_ngột: "suddenly, abruptly, unexpectedly, by surprise",
  đột: "to act suddently, abruptly",
  mât_chức: "lose their position",
  mât: "lose, lost",
  chức: "position, title, function",
  đi_tù: "go to jail",
  đi: "go to",
  tù: "jail, prison",
  tra: "investigation",
  điều_tra: "to investigate",
  tai: "ear; calamity, catastrophe",
  tai_tiếng: "scandal, bad reputation",
  danh: "name, (reputation, fame)",
  bại: "to lose, to be defeated, to fail",
  liệt: "to be paralyzed, weak, deficient",
  thi: "to test, to compare, to give",
  dụ: "to instruct, compare",
  như: "like, as, for example",
  bố_thí: "give alms, not charity.",
  triều_tiên: "korea, korean",
  đại: "big great",
  hàn: "cold",
  đại_hàn: "korea",
  cao_ly: "korea",
  lãnh_đạo: "leader, to lead",
  lãnh: "to lead",
  lĩnh: "to recieve",
  qua_đời: "past life",
  tổng_thống: "president",
  ai_cập: "egypt",
  trong: "in",
  nhà: "home",
  nhà_tù: "jail",
  phó: "vice, assistant",
  tử: "to die",
  ở: "in, at",
  mỹ: "united states",
  đại_sứ: "ambassador",
  đại: "to substitute, represent",
  đại_diện: "represent",
  diện: "face",
  ám_sát: "to assassinate",
  ám: "to be blackened by, haunted",
  sát: "to kill",
  tân: "new",
  Nhật: "japan",
  quôc: "china",
  trên_phố: "street",
  phố: "city",
  đường: "street",
  con_đường: "road",
  ung_thư: "cancer",
  ung: "ulcer, boil, abscess, cancer",
  siêu: "super",
  sao: "star",
  phát_thanh: "to broadcast",
  phát_thanh_viên: "broadcaster",
  phát: "to distribute; to emit, utter; to start, to breakout",
  thanh: "sound; tone, noise",
  viên: "offical, officer",
  tình_dục: "sexual desire",
  vì: "because-by",
  nhưng_mà: "but",
  tuy_rằng: "though-that",
  rất: "very",
  họ: "they, family name",
  họ_hàng: "relatives",
  bữa: "meal",
  chiều: "afternoon",
  nó: "it",
  lịch: "calender",
  thử_tướng: "prime minister",
  tướng: "generals",
  thử: "to guard, defend; to watch; to keep, observe.",
  tay: "hand",
  xử_tử: "execution",
  xử: "to decide, regulare, duge",
  tham_mưu_trưởng: "chief of staff",
  trưởng: "to be the oldest in the family, head, chief, general",
  thống_đốc: "governor",
  thống: "all, whole, to govern",
  đốc: "to oversee, supervise, manage, administer, to govern",
  ngân_hàng: "bank",
  ngân: "silver",
  hàng: "row, line, ranks",
  hoá: "merchandise, goods, wares, cargo",
  ương: "central",
  cũ: "to be old, used",
  cựu: "former",
  nước_ý: "italy",
  lãnh_án: "to receive sentence",
  năm: "year",
  giây: "seconds",
  mùa: "season",
  hè: "summer",
  thu: "fall",
  đông: "winter",
  thế_kỷ: "century",
  ngày_sinh: "date of birth",
  tội: "sin",
  trôn: "to flee, escape, evade",
  trốn_thuế: "to dodge taxes",
  nam_phi: "south africa",
  phi: "africa",
  phi_châu: "africa",
  châu: "continent",
  tập_đoàn: "community || to be collective",
  tập: "to gather, unite",
  đoàn: "band, flock, group; body, train",
  khai_thác: "to exploit (land, resources)",
  khai: "to open",
  thác: "to open up, enlarge, exploit",
  bạch_kim: "platinum",
  bạch: "white",
  trắng: "white",
  từ_chức: "to resign",
  chức: "office, position, title, function",
  sau: "after",
  biểu_tình: "demonstrate",
  biểu: "to express, manifest, demonstrate",
  tình: "feeling, sentiment; condition, state",
  thợ: "worker, craftman",
  thợ_mỏ: "miner",
  mỏ: "mine",
  bộ: "section, part, department (government), minister",
  bộ_quốc: "national defense",
  phòng: "to guard against, prevent",
  nga: "russia",
  sa_thải: "to fire, purge, dishonorable discharge",
  bị_sa: "to fall",
  bị_thải: "to dismiss, discard",
  lừa: "to cheat, to decieve, trick",
  lừa_đảo: "to lie, to turn upside down.",
  đối: "(adj) to reply, to oppose, to cope with",
  mặt: "face",
  tham_nhũng: "to be corrupt",
  tham: "greed, greedy",
  cáo_buộc: "to be accused",
  buộc: "to bind, fasten; to accuse, charge",
  giám_đôc: "director",
  giám: "to supervice, dired, examine, control",
  đôc: "to oversee, supervice, manage, administer",
  bồ: "friend, pal, girlfriend, boyfriend",
  nhí: "young small",
  thủ_tướng: "prime minister, premier",
  phó_thủ_tướng: "deputy preminer; vice",
  gây: "to being about, cause, occasion",
  tai_nạn: "accident",
  nạn: "accident, danger, misfortune, mishap, calamity, disaster, catastrophe",
  chết: "to die",
  vào_tù: "go to jail",
  vào: "to go in, to come in, to enter; against",
  thứ_trưởng: "undersecretary",
  thứ: "second vice, under",
  quốc_phòng: "department of defense",
  chủ_tịch: "chairman",
  tịch: "register, roll, citizenship, sleeping mat, feast",
  hội_đồng: "meeting, board, council",
  hội: "to assemble, gather, meet. assocication, society",
  đồng: "field, flat land, rice field, copper, brass, coin, bronze, piastre",
  quản_trị: "administer, administration",
  quản: " to manage, control, take care of adminster, oversee",
  kiêm: "to cumulate (functions)",
  đuối: "drowning",
  thứ: "rank, order, sort, type, time; inferior in quality; second, vice, under; to be ordinary, numerous.",
  khí: "air",
  thán: "coal, charcoal",
  ứng_cử: "to be candidate (in election)",
  ứng: "to respond",
  ứng_cử_viên: "candidate",
  cử: "to appoint, send (an official)",
  sát_hại: "murder",
  hại: "to harm",
  tử_nạn: "to die",
  cảnh_sát: "police, policemen",
  cảnh: "landscape, view, scenery, sight, scene, to warn, to arouse, alarm police",
  dựa_vào: "to lean against",
  dựa: "to lean",
  dữ_kiện: "data",
  dữ: "to be fierce, ferocious, wicked",
  sự_kiện: "fast",
  đó: "those, that",
  có_thể: "can, could, to be able to, perhaps, may be, possibly",
  thể: "ability",
  thấy: "to see",
  thấy_được: "can see",
  sặp: "to be about to; soon",
  sặp_tơi: "to come, arrive",
  sặp_đến: "coming soon",
  sẽ: "will",
  con_sẻ: "sparrow",
  còn: "to remain, to have left; still",
  nhân: "man, mankind, person, individual",
  vật: "thing, object, creature, being",
  quan_trọng: "to be important, vital; gravity",
  cường: "to be strong, powerful",
  mạnh: "to be strong, powerful",
  cường_quốc: "power, great nation",
  cho_đến: "until",
  đến: "to arrive(at), to come(to), to get(to), rearch",
  tiểu_quôc: "small-nation",
};

console.log(vocab_1);
